# Generated by Django 4.0.2 on 2022-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associatesmastermodel',
            name='specialization',
        ),
        migrations.AddField(
            model_name='associatesmastermodel',
            name='specialization',
            field=models.ManyToManyField(to='authentication.SpecializationModel'),
        ),
    ]
